#Conexión de bdd
server:
  port: 25060

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:strangeraccounts-do-user-12861954-0.b.db.ondigitalocean.com
    username: doadmin
    password: AVNS_Tpe9Vf9nhC8cyQOA9mj
