###Test de gaming
GET http://localhost:25060/api/v1/gaming/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtaXJrb2FsYXJjb242QGdtYWlsLmNvbSIsImlzcyI6InVjYiIsImdydXBvIjpbIkNsaWVudGUgbm9ybWFsIl0sInJlZnJlc2giOmZhbHNlLCJleHAiOjE2Njk4MTA4MDh9._f4ZPl5oJsNKxQuWuLd7hLJVaa1jR4dNn8uq2XcKjg8