### Consultamos el usuario autenticado
GET http://localhost:25060/api/v1/userapi/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbml0YS5nYXJjaWFAZ21haWwuY29tIiwiaXNzIjoidWNiIiwiZ3J1cG8iOlsiQ2xpZW50ZSBub3JtYWwiXSwicmVmcmVzaCI6ZmFsc2UsImV4cCI6MTY2OTIwODQzOH0.I8yzJj17R1Grq4MCqUQoKlYyKjGehrVZzauEbwwFJHI